### ISSUE TITLE
TableView cell offset incorrect, UI broken

### ISSUE THREAD

**Issue by ubapsi** [Uncommon/Xit#460] opened 2021-03-17 12:01 UTC
![screen](https://user-images.githubusercontent.com/79262375/111464013-89785500-8720-11eb-95ef-bc18f264ba65.png)

The first cell is always shown at this position.

Additionally, switching between "History" and "Details" (upper right toolbar) does not work. One has to manually slide the divider up or down to split the two view accordingly. After the manual change you can click the two buttons again. This has to be repeated after each new launch.

macOS 11.2.2

**Comment by Uncommon** [comment] 2021-03-17 15:12
Looks like a duplicate of #452 which I just recently fixed :)

**Closed** 2021-10-01 22:28 UTC
